{
 "title": "Throughput",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "clab-bgp-R1",
   "type": "timeseries",
   "description": "Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ifHCInOctets{ifDescr=\"Management1\", instance=\"clab-bgp-R1\"}",
     "legendFormat": "{{ifDescr}}"
    },
    {
     "expr": "ifHCInOctets{ifDescr=\"Ethernet3\", instance=\"clab-bgp-R1\"}",
     "legendFormat": "{{ifDescr}}"
    },
    {
     "expr": "ifHCInOctets{ifDescr=\"Ethernet2\", instance=\"clab-bgp-R1\"}",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  },
  {
   "title": "clab-bgp-R1",
   "type": "timeseries",
   "description": "Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ifHCInOctets{ifDescr=\"Management1\", instance=\"clab-bgp-R1\"}",
     "legendFormat": "{{ifDescr}}"
    },
    {
     "expr": "ifHCInOctets{ifDescr=\"Ethernet3\", instance=\"clab-bgp-R1\"}",
     "legendFormat": "{{ifDescr}}"
    },
    {
     "expr": "ifHCInOctets{ifDescr=\"Ethernet2\", instance=\"clab-bgp-R1\"}",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  },
  {
   "title": "clab-bgp-R3",
   "type": "timeseries",
   "description": "Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ifHCInOctets{ifDescr=\"Management1\", instance=\"clab-bgp-R3\"}",
     "legendFormat": "{{ifDescr}}"
    },
    {
     "expr": "ifHCInOctets{ifDescr=\"Ethernet3\", instance=\"clab-bgp-R3\"}",
     "legendFormat": "{{ifDescr}}"
    },
    {
     "expr": "ifHCInOctets{ifDescr=\"Ethernet2\", instance=\"clab-bgp-R3\"}",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  },
  {
   "title": "clab-bgp-R4",
   "type": "timeseries",
   "description": "Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ifHCInOctets{ifDescr=\"Management1\", instance=\"clab-bgp-R4\"}",
     "legendFormat": "{{ifDescr}}"
    },
    {
     "expr": "ifHCInOctets{ifDescr=\"Ethernet3\", instance=\"clab-bgp-R4\"}",
     "legendFormat": "{{ifDescr}}"
    },
    {
     "expr": "ifHCInOctets{ifDescr=\"Ethernet2\", instance=\"clab-bgp-R4\"}",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  },
  {
   "title": "clab-bgp-R5",
   "type": "timeseries",
   "description": "Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ifHCInOctets{ifDescr=\"Management1\", instance=\"clab-bgp-R5\"}",
     "legendFormat": "{{ifDescr}}"
    },
    {
     "expr": "ifHCInOctets{ifDescr=\"Ethernet3\", instance=\"clab-bgp-R5\"}",
     "legendFormat": "{{ifDescr}}"
    },
    {
     "expr": "ifHCInOctets{ifDescr=\"Ethernet2\", instance=\"clab-bgp-R5\"}",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  }
 ]
}